---
driver:
  name: vagrant
  network:
     - ["private_network", {ip: "192.168.33.34"}]
     
provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[mytomcat::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
